# This is a basic workflow to help you get started with Actions

name: Change Receipt Example

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #This workflow contains a single job called "build"
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v4

  #     # Runs a single command using the runners shell
  #     - name: Run a one-line script
  #       run: echo Hello, world!

  #     # Runs a set of commands using the runners shell
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.

  change_request:
    # jobs that must complete successfully before this job will run
    #needs: build
    # type of machine to run the job on
    runs-on: ubuntu-latest
    name: 'ServiceNow DevOps Change'
    steps:
      - name: Echo Job ID
        run: echo $GITHUB_JOB
      - name: ServiceNow Change
        id: create
        # For custom action based change, remove or disable the 'deployment-gate' configuration and the 'deploy' step. Ensure to update to the latest version of the custom action, for e.g. ServiceNow/servicenow-devops-change@v5.1.0
        uses: ServiceNow/servicenow-devops-change@v5.1.0
        with:
          # Devops Integration Token
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          # ServiceNow Instance URL
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          # Orchestration Tool Id
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          # GitHub Context
          context-github: ${{ toJSON(github) }}
          abortOnChangeCreationFailure: true
          abortOnChangeStepTimeout: true
          # Display Name of the Job
          job-name: 'ServiceNow DevOps Change'
          # change-request: snDevOpsChange
          # Unsupported fields are: risk, impact, and risk_impact_analysis
          change-request: '{"attributes":{"requested_by":"3948666ae7012300dd926217c2f6a967","assignment_group":"287ee6fea9fe198100ada7950d0b1b73","priority": "2","comments": "This is a sample pipeline script to be added in your change step","work_notes": "Update this to work_notes","start_date": "2025-03-13 12:00:00","end_date": "2025-03-13 12:00:00"}}'
          # You can specify the requested_by attribute either with name or sys_id. Example: "requested_by":{"name": "Test User"} or "requested_by": "62826bf03710200044e0bfc8bcbe5df1"
          # You can specify the assignment_group attribute either with name or sys_id. Example: "assignment_group":{"name": "Change Approval Team"} or "assignment_group": "5f721d93c0a8010e015533746de18bf9"
          # start_date: This is the planned start date
          # end_date: This is the planned end date
          # For deployment gate based change, uncomment the 'deployment-gate' configuration and the 'deploy' step 
          #deployment-gate: '{"environment": "Prod", "jobName": "deploy"}'
      - name: Output CHG
        run: echo "change-request-number = ${{ steps.create.outputs.change-request-number }}" >> $GITHUB_STEP_SUMMARY
        

  deploy:
   name: 'Deploy'
   needs: change_request
   runs-on: ubuntu-latest
   #environment: Prod
   concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
   steps:
     - name: Run deployment scripts
       run: echo Completed Deployment
